### ISSUE TITLE
EOF Error

### ISSUE THREAD

**Issue by Flajt** [tshirtman/Buildozer-docker#4]
Hi, I followed your instructions but unfortunately, python throws an EOF Error. I will append the log soon. It's a failure on buildozers site. Maybe it has something to do with buildozer running as root?  
Here is my log:

> $ docker run -v  $PWD:/buildozer/ d7b6737d0240
Buildozer is running as root!
This is not recommended, and may lead to problems later. 
Are you sure you want to continue [y/n]? Traceback (most recent call last):
 File "/usr/local/bin/buildozer", line 11, in <module>
   sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/buildozer/__init__.py", line 1023, in run_command
    self.check_root()
  File "/usr/local/lib/python3.6/dist-packages/buildozer/__init__.py", line 1067, in check_root
    cont = input_func('Are you sure you want to continue [y/n]? ')
EOFError: EOF when reading a line`

I run docker on Windows. 
Edit: 
Just tried to create new user who is not root to avoid the error. Now the machine states: 
> buildozer.spec not found in directory. Aborting.

**Comment by zyn99** [comment]
use this command:

sudo docker run -it -v $PWD:/buildozer tshirtman/buildozer buildozer init .
-----------------------------------------
your real machine   : /home/yourname/pyjob/main.py   go in this folder
your docker:   /buildozer  ,because dockfile shows VOLUME /buildozer, this is a special folder
PWD maps your folder to the docker's folder /buildozer
how it works :

-it will give you a choice to input y/n : 
“Buildozer is running as root! this is not recommand..... etc ...   are you sure you want to contine?”
input y, you will get a   .spec file

**Comment by zyn99** [comment]
after  above work:
sudo docker run -it -v $PWD:/buildozer tshirtman/buildozer buildozer init .
--------
use this command:
sudo docker run -it -v $PWD:/buildozer tshirtman/buildozer buildozer android debug deploy new 
------

you may find out the string "buildozer android debug deploy new " is familar to you in a real machine as you did before.

and this will take a long time to finish works like 'install platform'..etc
